models_path: examples/experimental/eval/models

models:
  - name: model_PPO____R_10000__02_27_09_19_10_626_003200
    train_dataset_size: 10_000
    wandb: https://wandb.ai/emerge_/gpudrive/runs/PPO____R_10000__02_27_09_19_10_626/workspace?nw=nwuserdaphnecor
    trained_on: null